"use client";
import Header from "./src/components/common/header";
import { roboto } from "./styles/font";
import "bootstrap/dist/css/bootstrap.min.css";
import "../app/styles/globals.scss";
import Footer from "./src/components/common/footer";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 1000,
      once: true,
    });
    AOS.refresh();
  }, []);
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
